### ISSUE TITLE
Timer UX

### ISSUE THREAD

**Issue by zbraniecki** [tc39/proposal-intl-duration-format#1]
Is this proposal intended to address all of the uses from the original https://github.com/tc39/ecma402/issues/47 ?

If so, one that is specific but not mentioned in the README yet is the "timer UX" - `-00:34:12.230` - this is a format used by video players, audio players, stopwatches, timers etc.

If not, why not?

**Comment by sffc** [comment]
I think the Timer UX should absolutely be a goal.  Otherwise we can already do most of the proposal with Intl.NumberFormat + Intl.ListFormat.

**Comment by younies** [comment]
There is one of the  Formatting widths can support that (it is more smaller than narrow, I need to check it and I will update this comment. And if there is no any width that supports `-00:34:12.230`, we can introduce a new width.

**Comment by sffc** [comment]
ICU calls it "numeric".

Note how this might play into the logic for suppressing fields, because it definitely doesn't make sense to suppress minutes when you have hours and seconds and you are using numeric format.

**Comment by younies** [comment]
Yes, we covered it.
