### ISSUE TITLE
Time separator is also numbering system dependent?

### ISSUE THREAD

**Issue by anba** [tc39/proposal-intl-duration-format#108]
CLDR defines a numbering system dependent time separator in `ldml/numbers/symbols/timeSeparator`. 

For example, `da-u-nu-latn` uses the [time separator `"."`](https://github.com/unicode-org/cldr/blob/46417d02b129b8c3dffce8688672eef2a1bf74d5/common/main/da.xml#L5436), whereas `da-u-nu-arabext` falls back to the [root time separator `"٫"`](https://github.com/unicode-org/cldr/blob/46417d02b129b8c3dffce8688672eef2a1bf74d5/common/main/root.xml#L3039). 

But when reading the `timeSeparator` definition in <https://unicode.org/reports/tr35/tr35-59/tr35-numbers.html#Number_Symbols>, it's not clear to me when `ldml/numbers/symbols/timeSeparator` should actually be used resp. if we should include the numbering system when looking up the time separator. UTS 35 has this note:
> No CLDR locales are known to have a need to specify timeSeparator symbols that depend on number system; [...]. In the meantime, since CLDR data consumers can still request the timeSeparator symbol. it should match the symbol actually used in the [timeFormats](https://unicode.org/reports/tr35/tr35-59/tr35-dates.html#timeFormats) and [availableFormats](https://unicode.org/reports/tr35/tr35-59/tr35-dates.html#availableFormats_appendItems) items.

The default (= `"latn"` numbering system [1]) time separator seems to match what's used in `<timeFormats>` and `<availableFormats>`, except for `fr-CA`:
- https://github.com/unicode-org/cldr/blob/46417d02b129b8c3dffce8688672eef2a1bf74d5/common/main/fr_CA.xml#L2021
- https://github.com/unicode-org/cldr/blob/46417d02b129b8c3dffce8688672eef2a1bf74d5/common/main/fr_CA.xml#L2088

`fr-CA` uses separate time separators for each time unit, i.e. `"h"`, `"min"`, and `"s"`. 

UTS 35 also defines [durationUnit](https://unicode.org/reports/tr35/tr35-59/tr35-general.html#durationUnit), which uses a single time separator which isn't numbering system dependent. 

I'm currently a bit lost due to the conflicting definitions from UTS 35. Can we make this a bit more clear in the spec?

---

[1] `"latn"` numbering system and not `<defaultNumberingSystem>` for cases like `ur-IN`, which uses `"arabext"` as its default numbering system, but doesn't override `ldml/numbers/symbols[@numberSystem="arabext"]/timeSeparator`, so it's using the default from the `root` locale, which means `"٫"`.

**Comment by sffc** [comment]
TG2 consensus: https://github.com/tc39/ecma402/blob/master/meetings/notes-2022-12-08.md#time-separator-is-also-numbering-system-dependent-108
