### ISSUE TITLE
Do we have any Polyfill to use this? 

### ISSUE THREAD

**Issue by khawarizmus** [tc39/proposal-intl-duration-format#175]
I am wondering if there is an implementation for this proposal somewhere that someone can point me to since it's at stage 3

**Comment by ryzokuken** [comment]
There's https://github.com/formatjs/formatjs/tree/d95d21f1ea10a190f45968e909323e9af6992921/packages/intl-durationformat

**Comment by khawarizmus** [comment]
The implementation seems to be just an empty shell class. https://github.com/formatjs/formatjs/blob/d95d21f1ea10a190f45968e909323e9af6992921/packages/intl-durationformat/index.ts and the docs page point to a 404 https://formatjs.io/docs/polyfills/intl-durationformat So i wouldn't call that an implementation 😅

**Comment by khawarizmus** [comment]
@ryzokuken I have went ahead and raise an Issue there since it seems that that repo is trying to implement high quality polyfills for `Intl` https://github.com/formatjs/formatjs/issues/4257
