### ISSUE TITLE
`"fractional"` and `"numeric"` style options for sub-second units

### ISSUE THREAD

**Issue by DesmondWillowbrook** [tc39/proposal-intl-duration-format#205]
[Section 1.5 from the rendered TC39 proposal](https://tc39.es/proposal-intl-duration-format/#sec-properties-of-intl-durationformat-instances) says that:
> Intl.DurationFormat instances also have several internal slots that are computed by the [constructor](https://tc39.es/ecma262/#constructor):
> ...
> [[MillisecondsStyle]] is one of the String values "long", "short", "narrow", or **"fractional"** identifying the formatting style used for the milliseconds field.

(emphasis mine)

while [Table 3](https://tc39.es/proposal-intl-duration-format/#table-durationformat) says that:

Style Slot | Display Slot | Unit | Values | Digital Default
-- | -- | -- | -- | --
[[MillisecondsStyle]] | [[MillisecondsDisplay]] | "milliseconds" | « "long", "short", "narrow", **"numeric"** » | "numeric"

(emphasis mine)

This seems inconsistent and possibly incorrect.

**Comment by sffc** [comment]
The public API is "numeric" but in the spec it becomes "fractional" because it has distinct behavior.
