### ISSUE TITLE
Can this be used to replace the `ms` package?

### ISSUE THREAD

**Issue by styfle** [tc39/proposal-intl-duration-format#210]
There is a popular [ms](https://www.npmjs.com/package/ms) package on npm and I'm trying to see if there are any options that can do the same thing.

For example:

```js
ms(60000, { long: true })
// prints '1 minute'
```

I tried the same with DurationFormat but it didn't work as expected.

```js
new Intl.DurationFormat("en-US").format({ milliseconds: 60000 })
// prints '60,000 ms'
```

**Comment by sffc** [comment]
There is no arithmetic / unit conversion in `Intl.DurationFormat` itself. However, it will be coming soon via `Temporal.Duration`.

https://github.com/tc39/proposal-intl-duration-format/issues/10
