### ISSUE TITLE
Formatted numeric parts incorrectly handled

### ISSUE THREAD

**Issue by anba** [tc39/proposal-intl-duration-format#223]
Two issues:

1. PartitionDurationFormatPattern, step 4.e.i:
> 4.e.i. Append FormatNumericUnits(durationFormat, duration, unit, signDisplayed) to result.

This step doesn't handle the case when `FormatNumericUnits` returns an empty list.

Instead something like:

> 4.e.i. Let numericPartsList be FormatNumericUnits(durationFormat, duration, unit, signDisplayed).
> 4.e.ii. If numericPartsList is not empty, append numericPartsList to result.

----

2. FormatNumericUnits appends formatted elements to numericPartsList instead of using list-concatenation.

> 16.b. Append FormatNumericHours(durationFormat, hoursValue, signDisplayed) to numericPartsList.

Needs to be:

> 16.b. Let hoursParts be FormatNumericHours(durationFormat, hoursValue, signDisplayed).
> 16.c. Set numericPartsList to the list-concatenation of numericPartsList and hoursParts.

Same goes for the calls to `FormatNumericMinutes` and `FormatNumericSeconds`.

**Comment by ben-allen** [comment]
Thanks for these! I'm putting up a PR with commits resolving each of the issues you've identified right now.
