### ISSUE TITLE
Fields

### ISSUE THREAD

**Issue by zbraniecki** [tc39/proposal-intl-duration-format#3]
In the current proposal fields are described as a dash separated string `{fields: "hour-minute-second"}`.

I think it would be more javascripty to do `{fields: ["hour", "minute", "second"]}` or `{hour: true, minute: true, second: true}`.

**Comment by sffc** [comment]
Seems like a duplicate of #2, which has several issues inside.

**Comment by younies** [comment]
Yes, #2 will answer this question. I think we will have two fields
` 
{
  from: "second",
  to: "hour"
}
`

Therefore, the user can swap the fields without making errors

`
{
  from: "hour",
  to: "second"
}
`
is the same.

Also, the user can specify a start point or an endpoint


### start point
`
{
  from: "hour",
  to: undefined
}
`

### end point
`
{
  from:  undefined,
  to: "second"
}
`

We can change the names too. Follow #2 for more illustrations

**Comment by younies** [comment]
We are narrowing the discussion into issue #32
