### ISSUE TITLE
Move this proposal to be a part of `RelativeTimeFormat`

### ISSUE THREAD

**Issue by younies** [tc39/proposal-intl-duration-format#39]
Include all the added functionality in this proposal to the `RelativeTimeFormat`

**Comment by FrankYFTang** [comment]
i strongly oppose for doing so. RelativeTimeFormat carry different semantic than DurationFormat
The output format of RelativeTimeFormat mean to represent
1.  "a particular time" in the timeline which 
2. relative to a fixed time 
3. Relative to a fixed time currently implicit defined as Now.
Even if we extend the RelativeTimeFormat to  change 3) by additional option to change the reference point to a different time, it still expect to represent
1.  "a particular time" in the timeline which 
2. relative to a fixed time 
For example, let's say if we allow the RelativeTimeFormat to change the reference time to Jan 20, 2020, then format(100, "day") would be "100 days after Jan 20, 2020" and format(-7, "day") would be "7 days before Jan 20, 2020".

But what DurationFormat should do is to express
1. the "amount" of time- unrelated to a reference point in the timeline. 

notice the difference between "a particular time relative to" and "amount of" are two very different concepts, just like "+" and "-" are two very different concept/operation on the same data type.
