### ISSUE TITLE
Name: DurationFormat vs DurationFormatter

### ISSUE THREAD

**Issue by littledan** [tc39/proposal-intl-duration-format#4]
ICU has been transitioning to "formatter" names for newer APIs, whereas ECMA-402 stuck with "format" names as it added new constructors. Should we stick with ECMA-402 conventions here?

**Comment by rxaviers** [comment]
I believe that means us asking ourselves: does the name correction outweighs the consistency of the object names?

**Comment by littledan** [comment]
Right. And just for context, when we've asked ourselves in the past, we answered, "Even though ICU decided on this name correction, we prefer consistency."

**Comment by younies** [comment]
I would like to use `DurationFormatter`. However, the ECMAScript committee uses `Format` in their names. I will try to discuss this in the next meeting.

**Comment by younies** [comment]
@littledan, We have discussed this issue last meeting and mostly agreed that we will go forward with `DurationFormat` name to be consistent.

Shall we close this issue, or do you have more questions about the issue?
