### ISSUE TITLE
Best fit

### ISSUE THREAD

**Issue by klimashkin** [tc39/proposal-intl-duration-format#6]
Is there a way to format using the best fit?

Show seconds only if there is no minutes/hours, seconds+minutes if there is not hours etc.

**Comment by klimashkin** [comment]
Oh, I didn't notice there is an option on the slides
[6. Hide-upper-limit with zero-valued.](https://docs.google.com/presentation/d/1IfyFfYBROZJkODWWHudBKuGkKvTzN_Pwn2iq1ZM4_JY/edit#slide=id.g6ea81dd3bf_0_82)

But probably points 6 and 7 can be replaced with the bestFit option all together

**Comment by younies** [comment]
Okay, I will add this  point to the design doc: Link TBD

**Comment by younies** [comment]
@klimashkin  We are discussing this issue in more details in this issue #32 , However, if you need more information or you think the other issue is not fulfilling your request. You can comment here or in the other issue.
