### ISSUE TITLE
The use of  text of "or below" is unclear and not well defined 

### ISSUE THREAD

**Issue by FrankYFTang** [tc39/proposal-intl-duration-format#71]
In step2-h of
1.1.3 PartitionDurationFormatPattern ( durationFormat, duration )
https://tc39.es/proposal-intl-duration-format/#sec-partitiondurationformatpattern

```
h. If style is "2-digit" or "numeric" and unit is ** "seconds" or below**, then
```

It is not clear what does "or below" mean, below in what? could we make it clear like

```
h. If style is "2-digit" or "numeric" and unit is ** one of "seconds", "milliseconds", "microseconds", or "nanoseconds" **, then
```

**Comment by ryzokuken** [comment]
This is fixed, closing.
