### ISSUE TITLE
Spec Feedback: Shane Carr

### ISSUE THREAD

**Issue by sffc** [tc39/proposal-intl-duration-format#84]
- 1.1.1 GetUnitOptions step 6: missing a `"`
- 1.1.2 PartitionDurationFormatPattern: you set maximumFractionDigits but not minimumFractionDigits.  My understanding was that we wanted to set both when the fractionalDigits option is present.  For example, we should be able to display "1.5 seconds" by default or "1.50 seconds" if fractionalDigits is set to 2.

Maybe more later

**Comment by ryzokuken** [comment]
> 1.1.1 GetUnitOptions step 6: missing a "

Fixed

> 1.1.2 PartitionDurationFormatPattern: you set maximumFractionDigits but not minimumFractionDigits. My understanding was that we wanted to set both when the fractionalDigits option is present. For example, we should be able to display "1.5 seconds" by default or "1.50 seconds" if fractionalDigits is set to 2.

Fair, will make a PR to address this.
