### ISSUE TITLE
PartitionDurationFormatPattern need to handle undefined field in duration 

### ISSUE THREAD

**Issue by FrankYFTang** [tc39/proposal-intl-duration-format#90]
In the proposal, there are two places calling PartitionDurationFormatPattern with the value return by ToPartialDuration.

https://tc39.es/proposal-intl-duration-format/#sec-Intl.DurationFormat.prototype.format
```
1.4.3 Intl.DurationFormat.prototype.format ( duration )
...
3. Let record be ? ToPartialDuration(duration).
4. Let formatted be ? PartitionDurationFormatPattern(df, record).
```
and
https://tc39.es/proposal-intl-duration-format/#sec-Intl.DurationFormat.prototype.formatToParts
```
1.4.4 Intl.DurationFormat.prototype.formatToParts ( duration )
...
3. Let record be ? ToPartialDuration(duration).
4. Let formatted be ? PartitionDurationFormatPattern(df, record).
```

Notice, in ToPartialDuration
https://tc39.es/proposal-temporal/#sec-temporal-topartialduration
some of the field might be "undefined"

But inside 1.1.2 PartitionDurationFormatPattern ( durationFormat, duration )
https://tc39.es/proposal-intl-duration-format/#sec-partitiondurationformatpattern

step 2-k-i
```
i. Set value to duration.[[Microseconds]] + duration.[[Nanoseconds]] / 1000.
```
but either duration.[[Microseconds]] and duration.[[Nanoseconds]] could be undefined.

and step 2-k-ii-1
```
1. Set value to duration.[[Milliseconds]] + value / 1000.
```
duration.[[Milliseconds]]  could be undefined
and step 2-k-ii-2-a
```
a. Set value to duration.[[Seconds]] + value / 1000.
```
duration.[[Seconds]] could be undefined

and step 2-l-i
```
i. Set value to duration.[[<valueSlot>]].
```
any duration.[[<valueSlot>]] could be undefined and resulting value is undefined
but then 2-p
```
p. Let num be ! FormatNumeric(durationFormat.[[NumberFormat]], value).
```
will pass undefined as 2nd argument to FormatNumeric
and step 2-t-ii
```
ii. Let prv be ! ResolvePlural(pr, value).
```
will pass undefined as 2nd argument to ResolvePlural

I don't think any of above are correct.

@sffc @ryzokuken

**Comment by sffc** [comment]
Discussion 2021-01-13: https://github.com/tc39/ecma402/blob/master/meetings/notes-2022-01-13.md#partitiondurationformatpattern-need-to-handle-undefined-field-in-duration-90

Conclusion: Treat undefined as 0.
