### ISSUE TITLE
Should we verify if duration object it's correct  when using '-' ?

### ISSUE THREAD

**Issue by romulocintra** [tc39/proposal-intl-duration-format#99]
Given the example :

```
new Intl.DurationFormat("fr-FR", { style: "long" }).format({
    hours: 1,
    minutes: -46,
    seconds: -40,
});
```

Should we have specified something that checks the validity of the duration to ensure that all properties have the "-" sign similar to checks done in temporal with  [durationsign](https://tc39.es/proposal-temporal/#sec-temporal-durationsign)?

**Comment by ryzokuken** [comment]
This was an oversight in the `DurationFormat` spec, thanks for spotting this.
